### ISSUE TITLE
Some Channels not being deleted users leave.

### ISSUE THREAD

**Issue by ChillFish8** [gregzaal/Auto-Voice-Channels#14]
Seems sometimes the bot forgets about certain channels and doesnt delete them,
seems to need to have enough voice state event for it to update and clear these

**Comment by gregzaal** [comment]
Can you reproduce this? Apart from the ol [phantom channels](https://github.com/discordapp/discord-api-docs/issues/1304) issue, as far as I know the bot will always somehow eventually delete any channels that it made.

**Comment by ChillFish8** [comment]
Could just be a long wait time before theyre deleted.

**Comment by gregzaal** [comment]
Actually you might be on to something.

![2020-02-18_12-01-24_Discord](https://user-images.githubusercontent.com/5604661/74725513-a81eca80-5246-11ea-8c5c-56281a87da63.png)

You made this channel, and 15m later it's still there. Running `info` on the channel ID shows:

```
Server: ◯ Dots Bots Support 601015720200896512
Name: 1: ハーリ-さん (CF8) | PyCharm | 0 friends
(1: 12495 12540 12522 -12373 12435  (CF8) | PyCharm | 0 friends)

0 Members:

0 Games:
```

The settings file shows:
```
   "secondaries":{
    "679262665884958731":{
     "creator":290923752475066368,
     "tc":679262674198069258,
     "tcr":679262672385998878
    }
   },
```

So it knows the channel exists, and it knows it's empty, but for some reason it's not getting deleted.

I don't know why it wasn't deleted in `on_voice_state_update`, but it should still get deleted in `check_empty`.
