### ISSUE TITLE
Add uptime to Ping command

### ISSUE THREAD

**Issue by gregzaal** [gregzaal/Auto-Voice-Channels#16]
Would be nice to show how long the bot has been alive as an indication of stability.

This could either be time since startup, or time since last connection (`on_shard_ready`).
Or both ¯\\\_(ツ)\_/¯.

**Comment by ChillFish8** [comment]
Ended up adding this to the `stats` command seemed to make a bit more sense rather than the ping command. Altho to get days, hours etc... client now has a up_time() function which returns Days, Hours, Minutes, Seconds

**Comment by gregzaal** [comment]
Yeah it's also good to have in stats, but adding it to `ping` would also allow everyone to see it and get an idea of stability.
