### ISSUE TITLE
Enable all commands if self-hosted

### ISSUE THREAD

**Issue by gregzaal** [gregzaal/Auto-Voice-Channels#3]
Atm most of the patreon integration is still in the code, help docs, etc. This should all be removed/hidden and all commands and features should work unless `patreon_info.py` is present.

**Comment by nick-potts** [comment]
I just added `return True` in the is_gold func

**Comment by ChillFish8** [comment]
This still need doing?

**Comment by gregzaal** [comment]
Not really. All the help docs still say "gold only", but I guess it doesn't matter.
