### ISSUE TITLE
Can't seem to get the bot to update channel names

### ISSUE THREAD

**Issue by DatsiK96** [gregzaal/Auto-Voice-Channels#66]
I'm using my own hosted bot. Followed the directions on it. Everything works. Except it doesn't update the name of the channel. So if I join in a channel, it counts 1 person in it, no matter how many people join. It only shows the game that people were playing on the name, when they joined, but not if it changes.

Any idea where I can start looking for troubleshooting? Or what information I can provide you for help?

Thanks.

**Comment by bl0m1** [comment]
I also had this issue, fixed it and created a pr: https://github.com/gregzaal/Auto-Voice-Channels/pull/67 :)

**Comment by gregzaal** [comment]
@DatsiK96 Discord has a rate limit for renaming channels, the bot only checks to rename every 10 minutes. Please read the docs and the faq, and use the support server for support questions.

@bl0m1 This has nothing to do with encoding logs.

**Comment by DatsiK96** [comment]
But it NEVER renames it... Not even after 10 minutes. I had multiple channels open for over 2 hours and it never renamed it.

**Comment by gregzaal** [comment]
Check your logs, and if you need further assistance, as I said use the support server.
