### ISSUE TITLE
Use a .env file to store config.

### ISSUE THREAD

**Issue by RealCyGuy** [gregzaal/Auto-Voice-Channels#7]
Using a .env file as opposed to a .json file is more secure.

**Comment by gregzaal** [comment]
Why would a different extension make it more secure? Can you link to some docs about what format you're referring to?

**Comment by ChillFish8** [comment]
This isnt really necessary, .env files are fine for configs but so is json in every aspect. Both can do the same thing altho the .env would require a bit more working to do and wouldnt change anything significant in terms of performance or usability
