### ISSUE TITLE
Migrated SQLITE to MONGODB

### ISSUE THREAD

**Issue by kasepta** [gregzaal/Auto-Voice-Channels#70]
Maybe someone know, how to change sqlite to mongodb database,
because when i hosted in heroku, when bot restart, old channel won't deleted, because cannot can't read the database before in heroku.

**Comment by ChillFish8** [comment]
Bot doesnt use sqlite and no current system to use MongoDB. Please ask these sorts of questions in https://discord.gg/mywEXQN
