### ISSUE TITLE
self hosted bot template error

### ISSUE THREAD

**Issue by 1Euro7Cent** [gregzaal/Auto-Voice-Channels#72]
Every dynamic template except the @@num@@ and @@creator@@ doesn't work. They are shown as general or 0

**Comment by gregzaal** [comment]
Works fine for me, you likely need to update your d.py and enable intents. See the support server if you need help.

**Comment by 1Euro7Cent** [comment]
Sorry for asking here but no one react with a useful message on the discord. So ill ask it here. How do I enable the intents. And what is d.py. sorry but I normally use JS and this is new for me. my DC is mrballou#9055
