### ISSUE TITLE
vc/private doesn't work at all

### ISSUE THREAD

**Issue by Fargus5** [gregzaal/Auto-Voice-Channels#76]
I tested more than one time the feature vc/private.... in many categories of channels... but users join the channels everytime...
the solution that I use is to lock the channel after set it as private.

in this way it works... but if an users logout from the channel while it is locked... a new slot will be avaiable and someone else can join easy.

so private fonction doesn't work at all.

**Comment by gregzaal** [comment]
Works fine for me. If you need support for the free public bots, please use the [support server](https://discord.io/DotsBotsSupport).

**Comment by Fargus5** [comment]
XD... this is professionnalism

**Comment by Asherlam** [comment]
Well it works for me too

**Comment by vinanrra** [comment]
Works well for me too

**Comment by Fargus5** [comment]
no, it is very laggy the public bot but ok
