### ISSUE TITLE
Lot of problems

### ISSUE THREAD

**Issue by Fargus5** [gregzaal/Auto-Voice-Channels#77]
https://github.com/gregzaal/Auto-Voice-Channels/issues/76
It is interesting how all of you says that everything works good when the bot doesn't work at all

And it is more interesting that you lock and close the conversation without solving the errors... and more... the bot doesn't work anymore right now

![image](https://user-images.githubusercontent.com/20026629/104861054-8afaec00-592e-11eb-85c4-02a93ebce4ec.png)

![image](https://user-images.githubusercontent.com/20026629/104861071-9817db00-592e-11eb-8d2a-17330758cf45.png)

Channels not created at all
Channels doesn't delete

**Comment by Asherlam** [comment]
Try to use another avc bot

**Comment by ChillFish8** [comment]
The github is NOT the place for this, if you have an issue go to the support server instead of commenting here.

Especially in the support server look at info and updates channel before just re sending this same message in a channel.

**Comment by Fargus5** [comment]
GitHub has made exactly for this... but ok I will follow your suggestion 👍🏻

**Comment by Fargus5** [comment]
> Try to use another avc bot

what you mean?

**Comment by Asherlam** [comment]
> > Try to use another avc bot
> 
> what you mean?

you can try Avc Beta 
![Uploading image.png…]()
these are same

**Comment by gregzaal** [comment]
As we've already said, please use the support server. Github is not the place for these discussions.  It's clear you didn't read the readme of this repository nor the issue template.
