### ISSUE TITLE
Channels always being positioned above after adding ability to specify vc category

### ISSUE THREAD

**Issue by HandyHat** [gregzaal/Auto-Voice-Channels#87]
@dylian94 
It looks like 79bb765 broke channel positioning, as now secondary channels are always being created above the primary channel, even if they are set to be created below using `vc/toggleposition`. Reverting back to a66560e fixes this.

**Comment by gregzaal** [comment]
Reverted the patch, again.

@dylian94 This is the 2nd issue the patch has caused, so I'm not going to merge it back until several sources can prove it's stable.
