### ISSUE TITLE
When typed (prefix)help this comes out

### ISSUE THREAD

**Issue by mmatt625** [gregzaal/Auto-Voice-Channels#9]
`FileNotFoundError with command help, params_str: ``
Traceback (most recent call last):
  File "C:\Users\matt\Desktop\vc channels\Auto-Voice-Channels\commands__init__.py", line 160, in run
    r = await cmd.execute(ctx, params)  # Run command
  File "C:\Users\matt\Desktop\vc channels\Auto-Voice-Channels\commands\help_cmd.py", line 72, in execute
    with open("docs.md", 'r', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'docs.md'`

**Comment by ChillFish8** [comment]
This should of been downloaded when either cloning or Downloading the Zip, how are you runnning the main file?

**Comment by mmatt625** [comment]
I cloned via HTTPS. Should i just manually download docs.md then put it in my folder?

**Comment by ChillFish8** [comment]
is it not already in your directory?

**Comment by mmatt625** [comment]
just checked, it is

**Comment by ChillFish8** [comment]
Are you running the main bot file, if so how are you executing it?

**Comment by mmatt625** [comment]
i run the bot file by putting "C:\Users\matt\Desktop\vc channels\Auto-Voice-Channels\auto-voice-channels.py" in cmd

**Comment by ChillFish8** [comment]
ah, Dont do that.

You need to run the program using the Python Interpreture or IDE and run the file in the folder location,
Using CMD will make it look locally in the wrong place.

**Comment by mmatt625** [comment]
ah will do
