### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by gamesthings** [gregzaal/Auto-Voice-Channels#91]
Bot Is Having ERRORS offline

**Comment by gregzaal** [comment]
https://github.com/gregzaal/Auto-Voice-Channels

> ## Help:
> 
> For **all** issues and questions you have, first ask in our [Support Server](https://discord.gg/HT6GNhJ). 99% of questions have been asked before and already have a solution available. Read the FAQ, #status channel, and pinned messages.
> 
> If you're self-hosting and have an actual code bug to report, also first check in the Support Server for a solution and see if anyone else has the same problem. If someone can confirm your bug in their own self-hosted bot, then you may [open an issue](https://github.com/gregzaal/Auto-Voice-Channels/issues).
