### ISSUE TITLE
[BUG] AVC cannot create a channel unless given admin of server (Even if every permission is granted)

### ISSUE THREAD

**Issue by DatsiK96** [gregzaal/Auto-Voice-Channels#95]
Here is proof of the role and category permissions.
![catperms](https://user-images.githubusercontent.com/15705306/151749952-461e5bbe-d7fd-4909-a6e0-96492092b34a.png)
![roleperms](https://user-images.githubusercontent.com/15705306/151749966-1dfa3780-ebcd-47f6-8114-cbdf85461deb.png)

The voice channels are SYNCED with the category.

I know that the issues being presented looks like a *permissions* issue on my server's side. But I feel that unless I have gravely misunderstood how role based administration works, this may be more of an issue with a check somewhere in the bot that is expecting something that my server isn't providing.

There was another bot that expected the first channel in the server to be readable/writable and since it wasn't, the bot simply shut off, even though it had sufficient permissions to the channels by ID that it needed. (Unless of course, administrator, bypassing the read/write restriction on the first channel was granted)

My server does have very strict permissions set, everything is denied to @everyone by default and permission is granted and doled out by roles. I have a strong suspicion that something similar to the scenario is happening here. Though I do not know how to demonstrate it effectively. nor track down the issue itself.

I am willing to throw in any assistance I can offer to resolve the issue however. Let me know.

**Comment by gregzaal** [comment]
AVC absolutely does not require admin to work, I have many servers working fine without it. This is is more complicated than that, please read the FAQ here: https://wiki.dotsbots.com/en/FAQ#the-bot-tells-me-it-doesnt-have-permission-to-do-something-but-i-already-gave-it-those-permissions

AVC never checks to see if it can do something, it simply tries to do it and then Discord's API says "nope you can't do that". **I cannot solve permission issues in the bot, as this is entirely controlled by you** and your server configuration (and any bugs on discord's side, like I suspect this is).

**Comment by DatsiK96** [comment]
I don't understand... I've shown you that I've given it every permission to the role and category. I've confirmed that the channels themselves are synchronized with the categories. I've confirmed that the role itself is targeting the AVC bot. How is this an issue on my side? I've completely isolated permissions on my side I feel...

**Comment by DatsiK96** [comment]
Is there a debug mode I can turn on and do testing on, and see more information? Step by step calls to the discord.py etc?

**Comment by DatsiK96** [comment]
I guess my question is, does it interest the developer to discover what specific changes were made that made it stop working unless `very specific configurations` are met?

It doesn't say in the documentation what exact configuration is required. Does it interest you to find out if there is such a configuration that exists?

**Comment by gregzaal** [comment]
As I've said, I cannot solve this, as I understand it it's an issue with Discord itself. If you can find some trigger for this issue or workaround, feel free to share it in the support server or edit the wiki. As explained in the [readme](https://github.com/gregzaal/Auto-Voice-Channels#help), **GitHub is not the place for these discussions.** This is not a bug with AVC, and I don't appreciate the notification spam about it :)

**Comment by DatsiK96** [comment]
Sorry for the spam. Understood...
